### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostBot#2]
- [ ] on plugins enable phase, search for plugins commonly found on servers
    1. Economy Plugins
    2. 
    3. MyPlots
- [ ] Look for LostTeam plugins
- [ ] add more chat commands
- [ ] name the bot "Jarvis" in chat
- [ ] add more to TODO list

**Comment by TheDeibo** [comment]
WIth the Jarvis, are we doing the same as we did for "hello"? So his reply would be "Hello $player"?

**Comment by jasonwynn10** [comment]
Not exactly, It will be `Jarvis > Hello $player`

**Comment by jasonwynn10** [comment]
I will make the Jarvis text bold and dark Blue

**Comment by TheDeibo** [comment]
But same but its gonna be the same principle

**Comment by jasonwynn10** [comment]
Yea. I plan on making it bilingual for other languages too, so we need to leave space for others probably as resources

**Comment by TheDeibo** [comment]
![Alt text](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/4/4c/Colors.png "Images")
So §1 and §l ? (TF::DARK_BLUE and TF::BOLD)

As for the languages, good luck xD

**Comment by jasonwynn10** [comment]
I have an easy method of getting the languages to work

**Comment by TheDeibo** [comment]
Okay. :) Great :+1:

I think I have a way of splitting the chatevent and joinevent. (it would tidy it a tiny bit) So, i will test it, and wait till work has stopped on the plugin to do it :3

**Comment by TheDeibo** [comment]
- [ ] Split the events up again.

ohh, it looks as if the events have been fighting xD

**Comment by jasonwynn10** [comment]
I think it will be fine if they are left as one file

**Comment by jasonwynn10** [comment]
@TheDeibo can you start work on a manager for PocketMoney or EconomyAPI for the plugin to interact with them? I want to start work on their commands asap.

**Comment by TheDeibo** [comment]
I will when I am not busy with college and other home life stuff.

I will get to it when I can :smiley;

**Comment by jasonwynn10** [comment]
That's a bummer... All I have to deal with is high school

**Comment by jasonwynn10** [comment]
BTW I completely scrapped my idea of  the multi-language support

**Comment by TheDeibo** [comment]
Okay.

**Comment by GlitchPlayer** [comment]
@jasonwynn10  Does MyPlot has a API for it?

**Comment by GlitchPlayer** [comment]
Btw, @jasonwynn10 _64FF00 said he might stop developing the PurePerms plugin

**Comment by jasonwynn10** [comment]
in development or not, it is still on of the most used plugins on servers

**Comment by GlitchPlayer** [comment]
kk. We might just modify it -3-
